### ISSUE TITLE
logos

### ISSUE THREAD

**Issue by tortinator** [krr-up/latex-collaboration-guide#2]
Need to settle how we share logos, also because they are not public,
and which and how many we pack into a submodule

**Comment by rkaminsk** [comment]
Why not make the logos public? We can still put them under a license that forbids reuse.

**Comment by tortinator** [comment]
Good idea. How would we do this?

**Comment by rkaminsk** [comment]
If we don't want to forbid reuse of the logos completely, we can use a [CC license](https://creativecommons.org/choose/). For example:

<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.

**Comment by rkaminsk** [comment]
Like this the logos can still be used by others. If you want to protect it further, we have to register it as a trademark.

**Comment by rkaminsk** [comment]
I made the logos repository public.
